//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iXOnlineWeb.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Book
    {
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string ISBN { get; set; }
        public string Author { get; set; }
        public string BookDescription { get; set; }
        public string Language { get; set; }
        public string Edition { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public int DaysAvailable { get; set; }
        public int MemberId { get; set; }
        public Nullable<bool> IsBookActive { get; set; }

        [NotMapped]
        public int AverageRating { get; set; }

    }
}
