//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iXOnlineWeb.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorLogId { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorSourceObject { get; set; }
        public string TargetSite { get; set; }
        public System.DateTime DateLogged { get; set; }
    }
}
