//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iXOnlineWeb.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int UserGuidId { get; set; }
        public string UserGuid { get; set; }
        public string UserRole { get; set; }
        public int UserRoleId { get; set; }
        public System.DateTime DateEnrolled { get; set; }
        public string MemberEnrolled { get; set; }
    }
}
