//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iXOnlineWeb.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessTable
    {
        public int AccessId { get; set; }
        public string UserGuidId { get; set; }
        public string RoleGuidId { get; set; }
        public System.DateTime DateEnrolled { get; set; }
        public int FunctionId { get; set; }
        public bool UserRevoked { get; set; }
        public string UserName { get; set; }
    }
}
